redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\elmur\\OneDrive\\Desktop\\Ai-Marketplace\\ai-marketplace\\.next"
publishOrigin = "config"
base = "C:\\Users\\elmur\\OneDrive\\Desktop\\Ai-Marketplace\\ai-marketplace"
command = "npm run build"
edge_functions = "C:\\Users\\elmur\\OneDrive\\Desktop\\Ai-Marketplace\\ai-marketplace\\edge-functions"
commandOrigin = "config"

[build.environment]
NEXT_PRIVATE_TARGET = "server"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/.netlify/functions/next"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]