[build]
  command = "npm run build"
  publish = ".next"
  edge_functions = "edge-functions"
  environment = { NEXT_PRIVATE_TARGET = "server" }

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200
